[package]
name = "tm-sync-edit-server"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }

env_logger = "0.11.3"
futures-util = { version = "0.3.30", features = ["sink"] }
log = "0.4.21"
tokio = { version = "1.38.0", features = ["net", "rt-multi-thread"] }
