[package]
name = "tm-sync-edit-server"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.5.0"
futures-util = { version = "0.3.30", features = ["sink"] }
gamebox = { git = "https://github.com/jussyDr/gamebox" }
tokio = { version = "1.35.1", features = ["macros", "net", "rt-multi-thread"] }
tokio-util = { version = "0.7.10", features = ["codec"] }
