[package]
name = "tm-sync-edit-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
postcard = { version = "1.0.8", features = ["use-std"] }
serde = { version = "1.0.197", features = ["derive"] }
tokio = "1.36.0"
tokio-util = { version = "0.7.10", features = ["codec"] }
