[package]
name = "tm-sync-edit-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
postcard = "1.0.8"
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.35.1", features = ["net"] }
tokio-util = { version = "0.7.10", features = ["codec"] }
